name: "terraform"
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: read
  pull-requests: write

jobs:
  presteps:
    runs-on: ubuntu-latest
    name: presteps
    outputs:
      env_name: ${{ steps.branch-based-env.outputs.env_name }}
    steps:
      - uses: actions/checkout@v2
      # Step to create and output env_name variable
      - id: branch-based-env
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "env_name=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "env_name=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            echo "env_name=dev" >> $GITHUB_ENV
          else
            echo "env_name=dev" >> $GITHUB_ENV
          fi

      - run: echo "I'm using variable ${{ steps.branch-based-env.outputs.env_name }}"

  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    needs: presteps
    environment: ${{ needs.presteps.outputs.env_name }}
    steps:
      - uses: actions/checkout@v3

      # - name: Setup terraform variables
      #   id: tfvars
      #   run: |-
      #     cat > pipeline.auto.tfvars <<EOF
      #     project_id="${{ env.PROJECT_ID }}"
      #     location="${{ env.LOCATION }}"
      #     EOF

      - uses: boxboat-github-practice/terraform-gcp-actions@main
        with:
          terraform-version: 1.5.3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
