name: "terraform"
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: boxboat-github-practice/terraform-gcp-actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          terraform-version: 1.3.4
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        #   tf-var-file: "boxboat-github-practice.tfvars"
