name: 'tf-apply'

on:
  workflow_dispatch:

jobs:
    setup:
        name: 'setup'
        runs-on: ubuntu-latest  
        environment: dev  
        defaults:
          run:
            shell: bash
    
        steps:
        - uses: 'actions/checkout@v3'

        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - name: HashiCorp - Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.3

        - name: Terraform Init
          run: terraform init
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
        - name: Terraform fmt
          id: fmt
          run: terraform fmt -check
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Apply
          id: apply
          run: terraform apply -auto-approve
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}